// utils/mailer.js
const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.ALERT_EMAIL,       // your gmail
    pass: process.env.ALERT_EMAIL_PASS  // app password
  }
});

exports.sendPeakAlert = async ({ to, deviceName, prediction, avg }) => {
  const mailOptions = {
    from: `"EnergyMinds AI" <${process.env.ALERT_EMAIL}>`,
    to,
    subject: "⚠️ Peak Energy Usage Alert",
    html: `
      <h2>Peak Energy Usage Alert</h2>
      <p>Your device <b>${deviceName}</b> is predicted to consume unusually high energy.</p>
      <table border="1" cellpadding="8" cellspacing="0">
        <tr>
          <th>Predicted Usage</th>
          <th>Recent Average</th>
        </tr>
        <tr>
          <td>${prediction.toFixed(4)} Wh</td>
          <td>${avg.toFixed(4)} Wh</td>
        </tr>
      </table>
      <p style="margin-top:15px;">
        This alert was generated by the Smart Energy AI system to help you save energy.
      </p>
      <p>— EnergyMinds Team</p>
    `
  };

  await transporter.sendMail(mailOptions);
};
